### PR TITLE
LT-7445 Add GetDefinitionOrGloss method to LexSense

### PR DESCRIPTION
**Pull request by RaymondLuong3**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/46)

### CODE REVIEW

**Comment by papeh** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/liblcm/46)*

**Comment by papeh** [comment]
We might not need the property anymore.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/liblcm/46#-:-L83rYEe5zjvgYaB1Bj5:b-p0fdsu)*

**Comment by RaymondLuong3** [comment]
I would take a little work, but I can see if I can pull it out of there

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/liblcm/46#-:-L83rew4q5dazcfL_XEs:b-4x4k1s)*

**Comment by RaymondLuong3** [comment]
Looks like there is just one thing stopping us. The LexEntryRef class also has a property called DefinitionOrGloss, and it will likely need significant investigation to completely remote it.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/liblcm/46#-:-L84H70bCl3DsXoGqxdd:b3lsfy8)*

**Comment by papeh** [comment]
:lgtm: removal of unnecessary properties can wait for another commit. Merging now so we can test.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/liblcm/46#-:-L885Z10AxlrXCc5J47Q:b535t2m)*

**Pull request merged**
