### PR TITLE
Work around lack of Zfs filesystem support

### PR DESCRIPTION
**Pull request by jasonleenaylor**
Test failures showed that zfs file systems are not
yet supported by Mono

* Don't use DriveInfo on linux to avoid a crash encountered
  when loading a project from a drive with an unuspported
  filesystem.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/118)

### CODE REVIEW

**Comment by marksvc** [comment]
:eyes:

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.LCModel/Infrastructure/Impl/XMLBackendProvider.cs, line 717 at r1](https://reviewable.io/reviews/sillsdev/liblcm/118#-Lxvqte45ML2mj1txa6s:-LxvsXRZDaT-iJDYlqZ_:bokfb3o) ([raw file](https://github.com/sillsdev/liblcm/blob/42bc5e0003a16d52bc67c11490a57e4d8e3b4c25/src/SIL.LCModel/Infrastructure/Impl/XMLBackendProvider.cs#L717)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Does this work in all cases if we have e.g. the following mount points: `/`, `/home`, `/home/foo` ? Or would `drives` in this case contain only one of the mounts?
</blockquote></details>

I'm not sure. I'd have to go to the c code in mono. The issue I am working around is found here:
https://github.com/mono/mono/blob/506406df064d21223d84a5c87c239f8d558bbb71/mcs/class/corlib/System.IO/DriveInfo.cs

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.LCModel/Infrastructure/Impl/XMLBackendProvider.cs, line 717 at r1](https://reviewable.io/reviews/sillsdev/liblcm/118#-Lxvqte45ML2mj1txa6s:-Lxvyxbz3GoHWRfWDClT:b-896fix) ([raw file](https://github.com/sillsdev/liblcm/blob/42bc5e0003a16d52bc67c11490a57e4d8e3b4c25/src/SIL.LCModel/Infrastructure/Impl/XMLBackendProvider.cs#L717)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Perhaps a fix could be
```
drives.sort_such_that_longest_paths_are_higher_in_list();
foreach(d in drives)
  if path starts with d.Name,
    driveForpath=d; 
    break;
```
</blockquote></details>

Done.

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.LCModel/Infrastructure/Impl/XMLBackendProvider.cs, line 729 at r1](https://reviewable.io/reviews/sillsdev/liblcm/118#-Lxvtsrg55R-LsvyT7OD:-Lxvz-im3wSBVin_5BEA:bnps4dc) ([raw file](https://github.com/sillsdev/liblcm/blob/42bc5e0003a16d52bc67c11490a57e4d8e3b4c25/src/SIL.LCModel/Infrastructure/Impl/XMLBackendProvider.cs#L729)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

oh, I think I would do "a filesystem type mono doesn't detect" 
</blockquote></details>

I've updated the comment, and moved it up into the conditional.

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.LCModel/Infrastructure/Impl/XMLBackendProvider.cs, line 730 at r1](https://reviewable.io/reviews/sillsdev/liblcm/118#-LxvqHV084UHub4lp3Ge:-Lxvz7RLC8-VTfolG0n7:b-j4wtcx) ([raw file](https://github.com/sillsdev/liblcm/blob/42bc5e0003a16d52bc67c11490a57e4d8e3b4c25/src/SIL.LCModel/Infrastructure/Impl/XMLBackendProvider.cs#L730)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It may help us in future attending to this if we also say something like: 

Mono's filesystem detecting is handled in w32file-unix.c. See `_wapi_drive_types[]` , `mono_w32file_get_logical_drive()`, `GetDriveTypeFromPath()`.







</blockquote></details>

I added this in a comment above the conditional that calls out why we even have one.

**Comment by marksvc** [comment]
:eyes:

**Pull request merged**
