### PR TITLE
Get Unit tests to run as 32bit and pass

### PR DESCRIPTION
**Pull request by jasonleenaylor**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/23)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[src/SIL.LCModel.Utils/SIL.LCModel.Utils.csproj, line 81 at r1](https://reviewable.io:443/reviews/sillsdev/liblcm/23#-L-2KwOBi9ksVQjluZUD:-L-2KwOBi9ksVQjluZUE:b-4d6iaq) ([raw file](https://github.com/sillsdev/liblcm/blob/58e63032ebe5251311c18f51e0e0fc02d88edfe8/src/SIL.LCModel.Utils/SIL.LCModel.Utils.csproj#L81)):*
> ```XML
>   </PropertyGroup>
>   <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
>     <OutputPath>bin\x86\Release\</OutputPath>
> ```

Doh! Grr.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/liblcm/23)*

**Comment by jasonleenaylor** [comment]
*[src/SIL.LCModel.Utils/SIL.LCModel.Utils.csproj, line 81 at r1](https://reviewable.io:443/reviews/sillsdev/liblcm/23#-L-2KwOBi9ksVQjluZUD:-L-2LTN03a1ifTYuPNIN:b-896fix) ([raw file](https://github.com/sillsdev/liblcm/blob/58e63032ebe5251311c18f51e0e0fc02d88edfe8/src/SIL.LCModel.Utils/SIL.LCModel.Utils.csproj#L81)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Doh! Grr.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/liblcm/23)*

**Comment by papeh** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/SIL.LCModel.Utils/SIL.LCModel.Utils.csproj, line 81 at r1](https://reviewable.io:443/reviews/sillsdev/liblcm/23#-L-2KwOBi9ksVQjluZUD:-L-2OvK7cU4_TYLDOpXg:b-3bi2d2) ([raw file](https://github.com/sillsdev/liblcm/blob/58e63032ebe5251311c18f51e0e0fc02d88edfe8/src/SIL.LCModel.Utils/SIL.LCModel.Utils.csproj#L81)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`..\..\artifacts\Release\`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/liblcm/23)*

**Comment by jasonleenaylor** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/SIL.LCModel.Utils/SIL.LCModel.Utils.csproj, line 81 at r1](https://reviewable.io:443/reviews/sillsdev/liblcm/23#-L-2KwOBi9ksVQjluZUD:-L-2yEDHCrRoBd3sXzOe:b-896fix) ([raw file](https://github.com/sillsdev/liblcm/blob/58e63032ebe5251311c18f51e0e0fc02d88edfe8/src/SIL.LCModel.Utils/SIL.LCModel.Utils.csproj#L81)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

`..\..\artifacts\Release\`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/liblcm/23)*

**Comment by marksvc** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tests/SIL.LCModel.Tests/SIL.LCModel.Tests.csproj, line 84 at r3](https://reviewable.io:443/reviews/sillsdev/liblcm/23#-L-31_asLGCOwGR2_Ac2:-L-31_atLmv9G1EyMFft:b-dahb3m) ([raw file](https://github.com/sillsdev/liblcm/blob/b29e5e306be250b18944920e1eb75fd7e610187d/tests/SIL.LCModel.Tests/SIL.LCModel.Tests.csproj#L84)):*
> ```XML
>     <OutputPath>..\..\artifacts\Debug\</OutputPath>
>     <DefineConstants>TRACE;DEBUG</DefineConstants>
>     <BaseAddress>285212672</BaseAddress>
> ```

Why this? And why manually FileAlignment? Oh I guess you're copying from something else. But I'm still curious why we would specify this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/liblcm/23#-:-L-321LxnLoqYl4Hj7oU:bnfp4nl)*

**Comment by papeh** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/liblcm/23#-:-L-392IFzrQ1b70NGQBO:bnfp4nl)*

**Pull request merged**
