### PR TITLE
update CommonServiceLocator to remove Microsoft.NETCore.App dependancy

### PR DESCRIPTION
**Pull request by hahn-kev**
closes https://github.com/sillsdev/languageforge-lexbox/issues/964

LCM references [CommonServiceLocator](https://www.nuget.org/packages/CommonServiceLocator/1.4.0), which in turn references [Microsoft.NETCore.App](https://www.nuget.org/packages/Microsoft.NETCore.App/)

this breaks various applications when attempting to include LCM. This PR updates that dependancy.

I also did a bit of refactoring to remove references to IServiceLocator in favor of the BCL interface IServiceProvider. I then provided some extension methods so there is source compatibility with this new version. If this is too big of a change and impacts FieldWorks too much then I can remove it and just upgrade the package. However the namespace that IServiceLocator is in has changed as part of the version change, so this seemed like a good time to remove our usage of this interface as it's non standard.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/302)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
:lgtm:
I need to build locally and verify this with FieldWorks, but it looks promising.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/302#-:-O257kzh1RtQmx0rsicm:b-toguyd)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hahn-kev)

___
*[`tests/SIL.LCModel.Tests/DomainImpl/NotebookTests.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/liblcm/302#-O257VqN0eQT6cWqa3V-:-O257VqN0eQT6cWqa3V0:bb7hquh) ([raw file](https://github.com/sillsdev/liblcm/blob/ee01993673efa5c9e1b574858f5e50388a166e21/tests/SIL.LCModel.Tests/DomainImpl/NotebookTests.cs#L5)):*
> ```Smalltalk
> // (http://www.gnu.org/licenses/lgpl-2.1.html)
> 
> using System;
> ```

huh?

**Comment by hahn-kev** [comment]
*[`tests/SIL.LCModel.Tests/DomainImpl/NotebookTests.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/liblcm/302#-O257VqN0eQT6cWqa3V-:-O27RfqW7XCZnSPLJrH_:b-flwxfi) ([raw file](https://github.com/sillsdev/liblcm/blob/ee01993673efa5c9e1b574858f5e50388a166e21/tests/SIL.LCModel.Tests/DomainImpl/NotebookTests.cs#L5)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

huh?
</blockquote></details>

`IServiceProvider` is declared in the system namespace.

**Comment by jasonleenaylor** [comment]
@hahn-kev here is an issue for FieldWorks we still need to work out
fw\Src\LexText\LexTextControls\LiftMergerSupportCodeAndClasses.cs(4227,38): error CS1061: 'ILcmServiceLocator' does not contain a definition for 'GetAllInstances' and no accessible extension method 'GetAllInstances' accepting a first argument of type 'ILcmServiceLocator' could be found (are you missing a using directive or an assembly reference?) [C:\Repositories\fwroot\fw\Src\LexText\LexTextControls\LexTextControls.csproj]

**Comment by jasonleenaylor** [comment]
Next in line:
fw\Src\LCMBrowser\LCMBrowserForm.Designer.cs(30,29): error CS1061: 'ILcmServiceLocator' does not contain a definition for 'GetInstance' and no accessible extension method 'GetInstance' accepting a first argument of type 'ILcmServiceLocator' could be found (are you missing a using directive or an assembly reference?) [C:\Repositories\fwroot\fw\Src\LCMBrowser\LCMBrowser.csproj]

**Comment by hahn-kev** [comment]
> Next in line: fw\Src\LCMBrowser\LCMBrowserForm.Designer.cs(30,29): error CS1061: 'ILcmServiceLocator' does not contain a definition for 'GetInstance' and no accessible extension method 'GetInstance' accepting a first argument of type 'ILcmServiceLocator' could be found (are you missing a using directive or an assembly reference?) [C:\Repositories\fwroot\fw\Src\LCMBrowser\LCMBrowser.csproj]

I think that one will just need a using statement. Though we could also just add the methods to the `ILcmServiceLocator` interface instead of using Extension methods. Not sure the best path forward there.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

With minor changes I got FieldWorks to build with all tests passing. A smoke test showed things apparently working.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/302#-:-O2fh-Dq6-sEJj2hcJht:bdhqqfc)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hahn-kev)

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/302)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hahn-kev)

**Pull request merged**
