### PR TITLE
LT-21760: Prevent Find and Fix from dropping homograph numbers

### PR DESCRIPTION
**Pull request by JakeOliver28**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/299)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`tests/SIL.LCModel.FixData.Tests/FwDataFixerTests.cs` line 869 at r1](https://reviewable.io/reviews/sillsdev/liblcm/299#-O-IQkAv-Gv8lzB2WAkj:-O-IQkAv-Gv8lzB2WAkk:b-c9y6aa) ([raw file](https://github.com/sillsdev/liblcm/blob/134e55514e48238e766ff778457138e112f48682/tests/SIL.LCModel.FixData.Tests/FwDataFixerTests.cs#L869)):*
> ```Smalltalk
> 		/// </summary>
> 		[Test]
> 		public void HomographNumberDrops()
> ```

I would name the test HomographFixerIgnoresAlternativeCitationForms

**Comment by jasonleenaylor** [comment]
*[`src/SIL.LCModel.FixData/HomographFixer.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/liblcm/299#-O-IR9QF2wMCZoXdugtm:-O-IR9QF2wMCZoXdugtn:bq0hvle) ([raw file](https://github.com/sillsdev/liblcm/blob/134e55514e48238e766ff778457138e112f48682/src/SIL.LCModel.FixData/HomographFixer.cs#L149)):*
> ```Smalltalk
> 				// if there was a citation form which matches the form of this MoStemAllomorph the MorphType
> 				// is not important to the homograph determination.
> 				if (m_Homographs.ContainsKey(rtFormText) || m_MorphTypeSort.Any())
> ```

Was this change still necessary?

**Review by JakeOliver28 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/299)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`src/SIL.LCModel.FixData/HomographFixer.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/liblcm/299#-O-IR9QF2wMCZoXdugtm:-O-ISgr3Crxd88VhzUn6:b-kkhzg8) ([raw file](https://github.com/sillsdev/liblcm/blob/134e55514e48238e766ff778457138e112f48682/src/SIL.LCModel.FixData/HomographFixer.cs#L149)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Was this change still necessary?
</blockquote></details>

I'm honestly not sure how necessary the change is, but it does safe guard against a potential KeyNotFoundException. Do you think this is significant enough to leave in or should I remove it? Or should I do some more digging to check if I can find a case where the error occurs?

**Comment by jasonleenaylor** [comment]
*[`src/SIL.LCModel.FixData/HomographFixer.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/liblcm/299#-O-IR9QF2wMCZoXdugtm:-O-IW8yJ02pU5w-TPkZP:b-bndm49) ([raw file](https://github.com/sillsdev/liblcm/blob/134e55514e48238e766ff778457138e112f48682/src/SIL.LCModel.FixData/HomographFixer.cs#L149)):*
<details><summary><i>Previously, JakeOliver28 (Jake Oliver) wrote…</i></summary><blockquote>

I'm honestly not sure how necessary the change is, but it does safe guard against a potential KeyNotFoundException. Do you think this is significant enough to leave in or should I remove it? Or should I do some more digging to check if I can find a case where the error occurs?
</blockquote></details>

I suppose there could be real data where this could cause a crash, so I think it is fine to leave it.

**Review by JakeOliver28 — COMMENTED** [review]
Test case renamed

> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/299#-:-O-IXg0-AV7ZZfbET9Kv:b-o7r8ap)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Pull request merged**
