### PR TITLE
Update icu nuget packages and icu version

### PR DESCRIPTION
**Pull request by jasonleenaylor**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/217)

### CODE REVIEW

**Review by papeh — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by papeh — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/217#-:-MwDyCMX7jF8IeJw6BsY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by papeh — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by papeh — APPROVED** [review]
> Reviewed 2 of 8 files at r3, 4 of 4 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Comment by jasonleenaylor** [comment]
___
*[src/SIL.LCModel/DomainServices/DataMigration/DataMigration7000019.cs, line 1140 at r6](https://reviewable.io/reviews/sillsdev/liblcm/217#-Mx03Edb-EvmqgSQmX4S:-Mx0qvsy8lYfar4Pehpe:bynvq1l) ([raw file](https://github.com/sillsdev/liblcm/blob/6fbfaca364aeb25aa4648674d1c9f2bc72394db8/src/SIL.LCModel/DomainServices/DataMigration/DataMigration7000019.cs#L1140)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

what if there are Private Use variants in addition to fonipa-x-etic?
</blockquote></details>

Currently this code will just drop them. Ooops. I'll fix it.

**Review by papeh — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/217)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[src/SIL.LCModel/DomainServices/DataMigration/DataMigration7000019.cs, line 1141 at r7](https://reviewable.io/reviews/sillsdev/liblcm/217#-Mx1B8k75UkG-0jTVqk_:-Mx1B8k75UkG-0jTVqka:undefined) ([raw file](https://github.com/sillsdev/liblcm/blob/83dedf8a570e6d9dd4efef0fe40c7b4e667ea7cd/src/SIL.LCModel/DomainServices/DataMigration/DataMigration7000019.cs#L1141)):*
> ```Smalltalk
> 							}
> 							string privateVariants = string.Join("-",
> 								newVariantList.Where(v=>v.Code != "fonipa").Select(v=>v.IsPrivateUse ? v.Code : ""));
> ```





_Suggestion:_
```Smalltalk
Where(v=>v.IsPrivateUse && v.Code != "fonipa").Select(v=>v.Code)
```

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/217)* status: 16 of 19 files reviewed, all discussions resolved (waiting on @papeh)

___
*[src/SIL.LCModel/DomainServices/DataMigration/DataMigration7000019.cs, line 1465 at r6](https://reviewable.io/reviews/sillsdev/liblcm/217#-Mx0A9vrEU6AWiZEKnHH:-Mx1DSVF8aWwry518lFX:b-ucfkn4) ([raw file](https://github.com/sillsdev/liblcm/blob/6fbfaca364aeb25aa4648674d1c9f2bc72394db8/src/SIL.LCModel/DomainServices/DataMigration/DataMigration7000019.cs#L1465)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

fyi, this is elegant
</blockquote></details>

Thanks.

**Review by papeh — COMMENTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/217)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
