### PR TITLE
Fix Change cl.exe file path

### PR DESCRIPTION
**Pull request by JamesPrabu**
* Changed cl.exe file path in GenerateKernelCs.proj

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/49)

### CODE REVIEW

**Comment by RaymondLuong3** [comment]
*[src/SIL.LCModel.Core/GenerateKernelCs.proj, line 5 at r1](https://reviewable.io/reviews/sillsdev/liblcm/49#-LAycL04ESnnx55spdrR:-LAycL04ESnnx55spdrS:b4z4isx) ([raw file](https://github.com/sillsdev/liblcm/blob/59a5b22b7d68b58b9cfc77da9c76eccb482566a8/src/SIL.LCModel.Core/GenerateKernelCs.proj#L5)):*
> ```XML
> 	<UsingTask TaskName="IdlImp" AssemblyFile="$(OutDir)SIL.LCModel.Build.Tasks.dll" />
> 	<PropertyGroup Condition="'$(OS)'=='Windows_NT'">
> 		<PreprocessCommand>"$(MSBuildProgramFiles32)\Microsoft Visual Studio $(MSBuildToolsVersion)\VC\bin\cl.exe" /E</PreprocessCommand>
> ```

This means that we will not longer be able to build in visual studio 2015. I'm ok with that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/49)*

**Comment by RaymondLuong3** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/49#-:-LAyceZW9ZLfyVoHu_iH:bnfp4nl)*

**Comment by RaymondLuong3** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/49)*

**Comment by RaymondLuong3** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/49)*

**Comment by jasonleenaylor** [comment]
James, this change I think has already been merged. I think locally you need to pull upstream and rebase. I am closing this PR because your commit is already merged into master here: https://github.com/sillsdev/liblcm/commit/a17d93d7af857626a0220d2647ec70f104bb64f6

**Pull request closed without merging**
