### PR TITLE
Merge branch `develop` into `feature/nuget`

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/187)

### CODE REVIEW

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 21 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/187)* status: 21 of 48 files reviewed, 1 unresolved discussion (waiting on @ermshiperete)

___
*[src/SIL.LCModel.Core/App.config, line 15 at r1](https://reviewable.io/reviews/sillsdev/liblcm/187#-MZY0yMY3lWD1BneEdqy:-MZY0yMY3lWD1BneEdqz:b-qfy0z1) ([raw file](https://github.com/sillsdev/liblcm/blob/ac71ab4152452c89f7114153dc3281a3fad24d01/src/SIL.LCModel.Core/App.config#L15)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>         <assemblyIdentity name="icu.net" publicKeyToken="416fdd914afa6b66" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-2.7.0.0" newVersion="2.7.0.0" />
>       </dependentAssembly>
>       <dependentAssembly>
>         <assemblyIdentity name="icu.net" publicKeyToken="416fdd914afa6b66" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-2.5.1.0" newVersion="2.5.0.0" />
>       </dependentAssembly>
> ```
</details>


Something doesn't seem quite right here.

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 17 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/187)* status: 38 of 48 files reviewed, 2 unresolved discussions (waiting on @ermshiperete)

___
*[tests/SIL.LCModel.Tests/App.config, line 22 at r1](https://reviewable.io/reviews/sillsdev/liblcm/187#-MZY1qux3ce9QC9pSj1R:-MZY1qux3ce9QC9pSj1S:bf80y1l) ([raw file](https://github.com/sillsdev/liblcm/blob/ac71ab4152452c89f7114153dc3281a3fad24d01/tests/SIL.LCModel.Tests/App.config#L22)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         <assemblyIdentity name="icu.net" publicKeyToken="416fdd914afa6b66" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-2.7.0.0" newVersion="2.7.0.0" />
>       </dependentAssembly>
>       <dependentAssembly>
>         <assemblyIdentity name="icu.net" publicKeyToken="416fdd914afa6b66" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-2.5.0.0" newVersion="2.5.0.0" />
> ```
</details>


Also not looking right.

**Review by ermshiperete — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/187)* status: 46 of 48 files reviewed, 2 unresolved discussions (waiting on @jasonleenaylor)

___
*[src/SIL.LCModel.Core/App.config, line 15 at r1](https://reviewable.io/reviews/sillsdev/liblcm/187#-MZY0yMY3lWD1BneEdqy:-MZY6xBq5i5r8IebnMZb:bq138ik) ([raw file](https://github.com/sillsdev/liblcm/blob/ac71ab4152452c89f7114153dc3281a3fad24d01/src/SIL.LCModel.Core/App.config#L15)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>         <assemblyIdentity name="icu.net" publicKeyToken="416fdd914afa6b66" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-2.7.0.0" newVersion="2.7.0.0" />
>       </dependentAssembly>
>       <dependentAssembly>
>         <assemblyIdentity name="icu.net" publicKeyToken="416fdd914afa6b66" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-2.5.1.0" newVersion="2.5.0.0" />
>       </dependentAssembly>
> ```

Something doesn't seem quite right here.
</blockquote></details>

Thanks for noticing. Done.
___
*[tests/SIL.LCModel.Tests/App.config, line 22 at r1](https://reviewable.io/reviews/sillsdev/liblcm/187#-MZY1qux3ce9QC9pSj1R:-MZY72HeDWOYNeN3eZWI:b-896fix) ([raw file](https://github.com/sillsdev/liblcm/blob/ac71ab4152452c89f7114153dc3281a3fad24d01/tests/SIL.LCModel.Tests/App.config#L22)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
>         <assemblyIdentity name="icu.net" publicKeyToken="416fdd914afa6b66" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-2.7.0.0" newVersion="2.7.0.0" />
>       </dependentAssembly>
>       <dependentAssembly>
>         <assemblyIdentity name="icu.net" publicKeyToken="416fdd914afa6b66" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-2.5.0.0" newVersion="2.5.0.0" />
> ```

Also not looking right.
</blockquote></details>

Done.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 21 of 22 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/187)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ermshiperete)

___
*[CHANGELOG.md, line 35 at r3](https://reviewable.io/reviews/sillsdev/liblcm/187#-MgMbbT7EK8XGVkMCoBD:-MgMbbT81DCCtH-PdPsi:bb5vu3i) ([raw file](https://github.com/sillsdev/liblcm/blob/b708ac369752c47572ccb2f0fc552ccaee1649da/CHANGELOG.md#L35)):*
> ```
> flexbridge
> ```
?

**Review by ermshiperete — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/187)* status: 51 of 52 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[CHANGELOG.md, line 35 at r3](https://reviewable.io/reviews/sillsdev/liblcm/187#-MgMbbT7EK8XGVkMCoBD:-MgeJXA93_Y_fZcf50SK:b18c263) ([raw file](https://github.com/sillsdev/liblcm/blob/b708ac369752c47572ccb2f0fc552ccaee1649da/CHANGELOG.md#L35)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> flexbridge
> ```
?
</blockquote></details>

Thanks for noticing. That's what you get from copy/paste :smile:  Done.

**Pull request merged**
