### PR TITLE
Fix LT-21870 and LT-21872 and boundary markers

### PR DESCRIPTION
**Pull request by jtmaxwell3**
Fixes LT-21870 (Import phonology - the given key was not present in the dictionary) by not writing out morphological conditions of phonological rules.
Fixes LT-21872 (Import Phonology crashes in Grammar area) by not deleting the PhonemeSet.
Fixes boundary marker problem reported by Ken by not deleting boundary markers in the PhonemeSet.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/311)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`tests/SIL.LCModel.FixData.Tests/TestData/HomographDrops/Test.bak` line 1 at r1](https://reviewable.io/reviews/sillsdev/liblcm/311#-O5-Nn99-6uv7wfeFKfZ:-O5-Nn99-6uv7wfeFKf_:bprmr7u) ([raw file](https://github.com/sillsdev/liblcm/blob/97f7618bf697443883bbee23fcb14672e1da21be/tests/SIL.LCModel.FixData.Tests/TestData/HomographDrops/Test.bak#L1)):*
> ```
> <?xml version="1.0" encoding="utf-8"?>
> ```

I think this was added by mistake.

**Review by jasonleenaylor — COMMENTED** [review]
I think it would be good to add a test project into the repository and add a specific use of your 'TestProjects' method to verify it.

> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/311#-:-O5-NyLG4eRVBKn8VzCz:b-couach)* status: 3 of 7 files reviewed, all discussions resolved

___
*[`tests/SIL.LCModel.Tests/DomainServices/PhonologyServicesTest.cs` line 1248 at r1](https://reviewable.io/reviews/sillsdev/liblcm/311#-O5-NKpN68QbPCwpvVV3:-O5-NKpN68QbPCwpvVV4:btjdabf) ([raw file](https://github.com/sillsdev/liblcm/blob/97f7618bf697443883bbee23fcb14672e1da21be/tests/SIL.LCModel.Tests/DomainServices/PhonologyServicesTest.cs#L1248)):*
> ```Smalltalk
> 		public void TestPCProjects()
> 		{
> 			TestProjects("C:\\Users\\PC\\source\\repos\\FieldWorks\\DistFiles\\Projects");
> ```

I'd rather keep this out of the repository even though it is convenient for your testing.

**Comment by jtmaxwell3** [comment]
Where would you like the test project stored?

What is a safe project to add?  The FieldWorks repository is public.

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 7 files at r1, 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/liblcm/311#-:-O5EWLCR6ZsdpqLFV1-3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jtmaxwell3)

**Pull request merged**
